version: "3"

services:
  poc-db:
    image: postgres:14
    container_name: poc-db
    ports:
      - "5432:5432"
    volumes:
      - poc-data:/var/lin/postgres/data
    environment:
      - POSTGRES_DB=poc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123

volumes:
  poc-data: